export enum ActionTypes {
  INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM',
  DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM',
  INCREMENT_BY_ENTHUSIASM = 'INCREMENT_BY_ENTHUSIASM',
  DECREMENT_BY_ENTHUSIASM = 'DECREMENT_BY_ENTHUSIASM',
  OTHER_ACTION = '__any_other_action_type__'
}

export default ActionTypes;